window.GC_PLACES = [
  {id:"cyberhub",name:"DLF CyberHub",category:"food",categoryLabel:"Food & drink",area:"Cyber City",price:"₹600–1,200",priceValue:600,priceType:"per person",tags:["Many options","Metro nearby","Open late"],distance:1.1,open:"Open until 11 PM",verified:"2 days ago",source:"Editorial sample",description:"A high-energy dining and culture district for days when you want options in one walkable place.",accent:"#bf7957",glyph:"C",cover:"Cyber\nHub",mapX:54,mapY:36,visit:"Good to visit now"},
  {id:"roots",name:"Roots – Café in the Park",category:"food",categoryLabel:"Food & drink",area:"Sector 29",price:"₹350–700",priceValue:350,priceType:"per person",tags:["Outdoor","Quiet","Local favourite"],distance:3.4,open:"Open until 10:30 PM",verified:"4 days ago",source:"Editorial sample",description:"A leafy, open-air café for slow breakfasts, long conversations and an easy evening reset.",accent:"#7a9c83",glyph:"R",cover:"Roots\nCafé",mapX:65,mapY:59,visit:"Good to visit now"},
  {id:"blue-tokai",name:"Blue Tokai Coffee Roasters",category:"food",categoryLabel:"Food & drink",area:"Golf Course Road",price:"₹250–500",priceValue:250,priceType:"per person",tags:["Laptop-friendly","Wi-Fi","Quiet"],distance:4.8,open:"Open until 10 PM",verified:"1 day ago",source:"Editorial sample",description:"Reliable coffee, a calm corner and enough room to turn a spare hour into focused time.",accent:"#6f8d9e",glyph:"B",cover:"Blue\nTokai",mapX:31,mapY:73,visit:"Good to visit now"},
  {id:"third-wave",name:"Third Wave Coffee",category:"food",categoryLabel:"Food & drink",area:"MG Road",price:"₹250–550",priceValue:250,priceType:"per person",tags:["Wi-Fi","Near metro","Work-friendly"],distance:2.6,open:"Open until 11 PM",verified:"3 days ago",source:"Editorial sample",description:"A dependable city café when you need coffee, a charging point and a quick meeting spot.",accent:"#a98666",glyph:"T",cover:"Third\nWave",mapX:69,mapY:45,visit:"Good to visit now"},
  {id:"circle-work",name:"The Circle.Work",category:"work",categoryLabel:"Workspaces",area:"Cyber City",price:"₹450–900/day",priceValue:450,priceType:"per day",tags:["Quiet","Power outlets","Community"],distance:1.3,open:"Open until 9 PM",verified:"2 days ago",source:"Editorial sample",description:"A polished coworking setting for remote workers, founders and teams that need a thoughtful base.",accent:"#5b847b",glyph:"C",cover:"The\nCircle",mapX:47,mapY:30,visit:"Good to visit now"},
  {id:"wework",name:"WeWork — DLF Two Horizon",category:"work",categoryLabel:"Workspaces",area:"Golf Course Road",price:"₹900–1,400/day",priceValue:900,priceType:"per day",tags:["Meeting rooms","Power outlets","Premium"],distance:5.2,open:"Open until 8 PM",verified:"5 days ago",source:"Editorial sample",description:"A premium workday option with meeting rooms, reliable infrastructure and a strong founder network.",accent:"#536f83",glyph:"W",cover:"Two\nHorizon",mapX:37,mapY:78,visit:"Good to visit now"},
  {id:"awfis",name:"Awfis — Udyog Vihar",category:"work",categoryLabel:"Workspaces",area:"Udyog Vihar",price:"₹500–1,000/day",priceValue:500,priceType:"per day",tags:["Flexible","Meeting rooms","Metro nearby"],distance:5.7,open:"Open until 8 PM",verified:"6 days ago",source:"Editorial sample",description:"Flexible desks and meeting rooms for people who need a professional base without a long commitment.",accent:"#9b8367",glyph:"A",cover:"Awfis\nUdyog",mapX:77,mapY:26,visit:"Good to visit now"},
  {id:"leisure-valley",name:"Leisure Valley Park",category:"public",categoryLabel:"Public spaces",area:"Sector 29",price:"Free",priceValue:0,priceType:"entry",tags:["Free","Outdoor","Walks"],distance:3.1,open:"Open until 9 PM",verified:"3 days ago",source:"Editorial sample",description:"A generous green pause in the middle of the city, ideal for a walk, a reset or an evening outdoors.",accent:"#789c68",glyph:"L",cover:"Leisure\nValley",mapX:58,mapY:64,visit:"Good to visit now"},
  {id:"tau-devi",name:"Tau Devi Lal Biodiversity Park",category:"public",categoryLabel:"Public spaces",area:"Sector 52",price:"Free",priceValue:0,priceType:"entry",tags:["Free","Nature","Outdoor"],distance:7.8,open:"Open until 7 PM",verified:"8 days ago",source:"Editorial sample",description:"A spacious green escape for a slower afternoon, especially when you want a little more distance from the glass towers.",accent:"#6e956c",glyph:"T",cover:"Tau Devi\nLal",mapX:18,mapY:54,visit:"Better before sunset"},
  {id:"biodiversity",name:"Aravalli Biodiversity Park",category:"public",categoryLabel:"Public spaces",area:"Vasant Kunj edge",price:"Free",priceValue:0,priceType:"entry",tags:["Free","Nature","Walking"],distance:9.6,open:"Open until 6:30 PM",verified:"10 days ago",source:"Editorial sample",description:"Native Aravalli landscape and walking paths for a quieter, more restorative city break.",accent:"#668f76",glyph:"A",cover:"Aravalli\nPark",mapX:11,mapY:78,visit:"Better before sunset"},
  {id:"museo",name:"Museo Camera",category:"events",categoryLabel:"Culture & events",area:"Gurugram",price:"₹250–400",priceValue:250,priceType:"entry",tags:["Culture","Indoor","Weekend"],distance:4.5,open:"Open until 7 PM",verified:"5 days ago",source:"Editorial sample",description:"A thoughtful photography museum for a culture-led afternoon away from the usual mall circuit.",accent:"#8a728d",glyph:"M",cover:"Museo\nCamera",mapX:28,mapY:45,visit:"Good to visit now"},
  {id:"thirtytwo",name:"32nd Avenue",category:"events",categoryLabel:"Culture & events",area:"Sector 15",price:"₹300–800",priceValue:300,priceType:"per person",tags:["Food","Events","Live music"],distance:4.1,open:"Open until 11 PM",verified:"2 days ago",source:"Editorial sample",description:"An easy all-evening neighbourhood destination for food, pop-ups, music and community energy.",accent:"#b47b63",glyph:"3",cover:"Thirty\nTwo",mapX:73,mapY:72,visit:"Good to visit now"},
  {id:"sector-market",name:"Sector 29 Evening Market",category:"food",categoryLabel:"Food & drink",area:"Sector 29",price:"₹150–400",priceValue:150,priceType:"per person",tags:["Budget","Street food","Open late"],distance:3.7,open:"Open until 11:30 PM",verified:"4 days ago",source:"Editorial sample",description:"A lively, budget-friendly cluster for a quick bite, a casual drink and a little people-watching.",accent:"#c18855",glyph:"S",cover:"Sector\n29",mapX:72,mapY:52,visit:"Good to visit now"},
  {id:"library",name:"Gurugram Public Library",category:"services",categoryLabel:"Useful services",area:"Old Gurgaon",price:"Free",priceValue:0,priceType:"entry",tags:["Free","Quiet","Study"],distance:6.2,open:"Open until 6 PM",verified:"7 days ago",source:"Editorial sample",description:"A useful, low-cost option for reading, studying and accessing a little quiet in a busy city.",accent:"#7d8fa0",glyph:"G",cover:"Public\nLibrary",mapX:81,mapY:64,visit:"Good to visit now"},
  {id:"sadar",name:"Sadar Bazaar",category:"services",categoryLabel:"Useful services",area:"Old Gurgaon",price:"₹100–500",priceValue:100,priceType:"typical spend",tags:["Local","Budget","Everyday"],distance:5.8,open:"Open until 9 PM",verified:"9 days ago",source:"Editorial sample",description:"The everyday side of Gurugram: practical shopping, local food and a more textured city rhythm.",accent:"#a47f63",glyph:"S",cover:"Sadar\nBazaar",mapX:83,mapY:78,visit:"Good to visit now"},
  {id:"huda-metro",name:"Huda City Centre Metro",category:"services",categoryLabel:"Useful services",area:"MG Road",price:"₹10–60/ride",priceValue:10,priceType:"typical fare",tags:["Metro","Connected","Accessible"],distance:2.4,open:"First train 5:15 AM",verified:"1 day ago",source:"Editorial sample",description:"A practical starting point for moving through the city without adding another cab ride to the day.",accent:"#6a8792",glyph:"M",cover:"Huda\nMetro",mapX:64,mapY:39,visit:"Good to visit now"},
  {id:"social",name:"Social — Cyber Hub",category:"events",categoryLabel:"Culture & events",area:"Cyber City",price:"₹500–1,000",priceValue:500,priceType:"per person",tags:["Networking","Food","Open late"],distance:1.5,open:"Open until 1 AM",verified:"3 days ago",source:"Editorial sample",description:"A familiar meeting point for after-work conversations, informal networking and late dinners.",accent:"#876b78",glyph:"S",cover:"Social\nCyber",mapX:59,mapY:24,visit:"Good to visit now"},
  {id:"project-cafe",name:"The Project Café",category:"food",categoryLabel:"Food & drink",area:"Sector 29",price:"₹450–800",priceValue:450,priceType:"per person",tags:["Design","Outdoor","Meetings"],distance:3,open:"Open until 11 PM",verified:"6 days ago",source:"Editorial sample",description:"A design-forward café with a relaxed atmosphere for a meeting that does not feel like a meeting.",accent:"#a18c72",glyph:"P",cover:"Project\nCafé",mapX:52,mapY:70,visit:"Good to visit now"},
  {id:"book-cafe",name:"The Book Café",category:"work",categoryLabel:"Workspaces",area:"Cyber City",price:"₹150–300",priceValue:150,priceType:"per person",tags:["Quiet","Reading","Wi-Fi"],distance:1.8,open:"Open until 8 PM",verified:"5 days ago",source:"Editorial sample",description:"A low-key reading and work corner for when you want a softer alternative to a busy coffee shop.",accent:"#718d85",glyph:"B",cover:"The Book\nCafé",mapX:42,mapY:43,visit:"Good to visit now"}
];

window.GC_MOTIVES = [
  {id:"food",icon:"◒",label:"Eat & drink",detail:"Good food, clearly priced"},
  {id:"work",icon:"⌘",label:"Work somewhere",detail:"Cafés, desks, quiet corners"},
  {id:"events",icon:"✦",label:"Find events",detail:"Culture, meetups, things to do"},
  {id:"public",icon:"⌁",label:"Take a break",detail:"Parks, walks, public spaces"},
  {id:"services",icon:"＋",label:"Get things done",detail:"Useful places and services"},
  {id:"explore",icon:"↗",label:"Explore the city",detail:"Follow your curiosity"}
];
window.GC_ROLES = ["Tech professional","Startup founder","Startup employee","Freelancer / remote","Student","Resident","Visitor"];
window.GC_NEIGHBOURHOODS = ["Cyber City","Sector 29","MG Road","Old Gurgaon","Golf Course Road","Udyog Vihar"];
window.GC_COORDS = {
  cyberhub: [77.0894, 28.4952], roots: [77.0323, 28.4672], "blue-tokai": [77.0941, 28.4425], "third-wave": [77.0923, 28.4595],
  "circle-work": [77.0887, 28.4959], wework: [77.0937, 28.4355], awfis: [77.0472, 28.5122], "leisure-valley": [77.0314, 28.4686],
  "tau-devi": [77.0826, 28.4298], biodiversity: [77.1501, 28.5204], museo: [77.0551, 28.4661], thirtytwo: [77.0362, 28.4546],
  "sector-market": [77.0328, 28.4663], library: [77.0167, 28.4605], sadar: [77.0221, 28.4619], "huda-metro": [77.0721, 28.4593],
  social: [77.0899, 28.4957], "project-cafe": [77.0352, 28.4688], "book-cafe": [77.0872, 28.4926]
};
